name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-22.04
    
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ryujin_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Apache AGE extension
        run: |
          git clone https://github.com/apache/age.git
          cd age
          make install PG_CONFIG=/usr/lib/postgresql/13/bin/pg_config
          psql -U postgres -d ryujin_test -c "CREATE EXTENSION IF NOT EXISTS age;"

      - name: Set up Elixir
        uses: erlef/setup-beam@v1.16.0
        with:
          elixir-version: '1.18.4'
          otp-version: '28.0'

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test
